### ISSUE TITLE
SNOW-830895: Can I keep async queries running when closing session?

### ISSUE THREAD

**Issue by hota911** [snowflakedb/snowpark-java-scala#36]
Hi,

I'd like to use AsyncJob to unload data to S3 asynchronously. 
Our service may be killed any time and session can be closed.
It seems all queries are canceled when the session is closed https://github.com/snowflakedb/snowpark-java-scala/blob/b5679a33b16a926890e5abaf21a7d00bd324d68f/src/main/scala/com/snowflake/snowpark/Session.scala#L1197
Is there way to run async job and keep it even when session is closed?

Thank you

**Comment by sfc-gh-jfreeberg** [comment]
Hi @hota911 -- Yes when the .close() method is called, the jobs will be killed... so don't call the .close() method. The server won't kill the jobs if the client disconnects. 

Let me know if you have any other questions!

CC @sfc-gh-bli
