### ISSUE TITLE
SNOW-876355: dataframe show throws out of memory 

### ISSUE THREAD

**Issue by sonalgoyal** [snowflakedb/snowpark-java-scala#45]
it seems dataframe show fetches rows to the client leading to out of memory errors for larger dataframes

**Comment by sfc-gh-jfreeberg** [comment]
@sonalgoyal -- Yes that's expected, .show() is an action and will fetch the entire DataFrame. If you're working with a dataset which exceeds the memory of the client, try using DataFrame.toLocalIterator() to incrementally fetch the results. 

More info: https://docs.snowflake.com/en/developer-guide/snowpark/java/working-with-dataframes#performing-an-action-to-evaluate-a-dataframe

**Comment by sonalgoyal** [comment]
Thanks for the link @sfc-gh-jfreeberg. Though it is an action, the documentation mentions. [printing 10 rows ](https://docs.snowflake.com/en/developer-guide/snowpark/java/working-with-dataframes#label-snowpark-java-dataframe-print-results) and my understanding was to use it like a debug in the flow, just like Spark. In my opinion, if it is 10 rows, the entire result set should not be brought to the client but limited on the warehouse.
