### ISSUE TITLE
SNOW-897574: Add built-in function regexp_replace

### ISSUE THREAD

**Issue by jbergeroncoveo** [snowflakedb/snowpark-java-scala#46]
The `regexp_replace` function is missing from the scala/java code base (but it is available in [python](https://docs.snowflake.com/ko/developer-guide/snowpark/reference/python/api/snowflake.snowpark.functions.regexp_replace.html#snowflake-snowpark-functions-regexp-replace)). Add that function in the `Functions` class/object.

**Comment by jbergeroncoveo** [comment]
Hello :smiley: I made the change on a branch locally. Any way I can push the branch for a pull request ?

**Comment by sfc-gh-bli** [comment]
Fixed in 
https://github.com/snowflakedb/snowpark-java-scala/pull/52
